# Generated by Django 3.1.14 on 2022-03-08 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Course'},
        ),
        migrations.RemoveField(
            model_name='courses',
            name='classes',
        ),
        migrations.AddField(
            model_name='courses',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.classes'),
        ),
    ]
