# Generated by Django 3.1.14 on 2022-03-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20220309_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='classes',
        ),
        migrations.AddField(
            model_name='courses',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Classes'),
        ),
    ]
