# Generated by Django 3.1.14 on 2022-03-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20220309_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'Class'},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={},
        ),
        migrations.RemoveField(
            model_name='classes',
            name='name',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='description',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='title',
        ),
        migrations.AddField(
            model_name='classes',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Courses'),
        ),
        migrations.AddField(
            model_name='classes',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='href',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='href',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
