# Generated by Django 3.1.14 on 2022-03-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_class_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Course', verbose_name='Дисциплины курса'),
        ),
        migrations.AlterField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='class',
            name='href',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на страницу курса'),
        ),
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/class/%Y/%m/%d', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='class',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название курса'),
        ),
    ]
