# Generated by Django 3.1.14 on 2022-03-12 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20220312_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_id',
            field=models.CharField(default=uuid.uuid4, help_text='Уникальный ID курса', max_length=200),
        ),
    ]
