# Generated by Django 3.1.14 on 2022-03-12 23:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0009_class_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
