# Generated by Django 3.1.14 on 2022-03-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20220313_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('number', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Groups', verbose_name='Присоединенные группы'),
        ),
    ]
