# Generated by Django 3.1.14 on 2022-03-13 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0013_auto_20220313_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='general_classes',
            field=models.ManyToManyField(blank=True, related_name='classes_general_set', to='courses.Course', verbose_name='Общие дисциплины курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/course/%Y/%m/%d', verbose_name='Картинка дисциплины'),
        ),
        migrations.AlterField(
            model_name='class',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, related_name='classes_set', to='courses.Course', verbose_name='Специальные дисциплины курса'),
        ),
        migrations.AlterField(
            model_name='class',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
