# Generated by Django 3.1.14 on 2022-03-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20220313_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='identifier',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
